### ISSUE TITLE
great

### ISSUE THREAD

**Issue by bitandalib** [pyhoon/Register-User-B4A#1]
that was great. do u know how can connect this login form to wordpress web??
thank u

**Comment by pyhoon** [comment]
Does your wordpress return json string after you pass in your login parameters? If yes, then it is possible.

**Comment by bitandalib** [comment]
I try it, but i cant. can u show me an example or connect to my pc and show me???

**Comment by pyhoon** [comment]
Do you use B4A to build the Android app? Why do you use Wordpress? You can build a simple backend using PHP. Learn to use PDO or MySQLi to connect to your MySQL database.

**Comment by bitandalib** [comment]
I can connect to MySQL. I made an app with B4A and connected to MySQL.
I don't know how login to wordpress with my app. I made a social site and i wanna use app for It.

**Comment by bitandalib** [comment]
I living in Iran and I can't find source to learn how connect to wordpress with web service or JSON.
I nedd learn for first time to how can do that

**Comment by pyhoon** [comment]
I am not sure what you want to do. Or you can use Webview to open the Wordpress site.

**Comment by bitandalib** [comment]
I wanna make an application same as Instagram but differently.
For first time I wanna learn how can connect to my web
but my web is wordpress and i don't know how connect to that database.

**Comment by bitandalib** [comment]
so I need how connect to wordpress.
I used B4A

**Comment by pyhoon** [comment]
You can build a separate PHP backend deploy in same hosting to read the same database and share the resources such as images. You don't need to connect to Wordpress. If you insist to connect to Wordpress, you can try to use some plugin to generate json output. Please remember that Wordpress is a web application which use session and cookie while you can build a backend which is stateless.

**Comment by bitandalib** [comment]
I got it.
Do you have any source or example for that?

**Comment by bitandalib** [comment]
for PHP

**Comment by pyhoon** [comment]
Have you checked my other repository? It is PHP backend for this B4A app.
https://github.com/pyhoon/Register-User-PHP

**Comment by bitandalib** [comment]
yes yes
for example i don't use create-member-table.sql 
i changed the parameters on the PHP files.
for example i changed user_id with user_login(wp_user on wordpress database).
is it correct or I use another thing?

**Comment by pyhoon** [comment]
May be you can read about Wordpress REST API https://developer.wordpress.org/rest-api/

**Comment by bitandalib** [comment]
thank you men
I got what happens, but I don't know how use that on B4A. becaus I study B4A just.
I know in first, app must be authentication  to server(site) with Clint ID and Clint Secret, and second the users have do that with them username and password.
but I don't know how do that.
can u show that to us with an example?

**Comment by pyhoon** [comment]
Maybe you set up a WordPress site and put some sample contents. Send me the database login when you have done.

**Comment by bitandalib** [comment]
hi
i found how can login

[new 4.txt](https://github.com/pyhoon/Register-User-B4A/files/3171051/new.4.txt)

I checked with a true user and fake user and thas work great.
but some wrong, when webview be activate, I'm out of every thing :|
u need to install 2 plugins
wp-rest api
wp-oauth 2.0
please check it

**Comment by bitandalib** [comment]
[new 4.txt](https://github.com/pyhoon/Register-User-B4A/files/3171050/new.4.txt)

**Comment by bitandalib** [comment]
I did it
this is sogreat
u need [JWT Authentication for WP REST API](https://wordpress.org/plugins/jwt-authentication-for-wp-rest-api/) and [WP REST API 2](https://github.com/WP-API/WP-API) plugins.
and replace your information in file:
[login.txt](https://github.com/pyhoon/Register-User-B4A/files/3171416/login.txt)
enjoy it
